apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.global.secretProviderClassName }} 
spec:
  provider: azure
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:                      # name of the mounted content to sync; this could be the object name or the object alias
    - key: AZURE-APP-INSIGHTS-CONNECTION-STRING
      objectName: AZURE-APP-INSIGHTS-CONNECTION-STRING
    - key: CBA-AZURE-BLOB-STORAGE-CONFIG-CONNECTION-STRING
      objectName: CBA-AZURE-BLOB-STORAGE-CONFIG-CONNECTION-STRING
    - key: CBA-ORM-HOST
      objectName: CBA-ORM-HOST
    - key: CBA-RABBITMQ-URI
      objectName: CBA-RABBITMQ-URI      
    - key: CBA-ORM-PORT
      objectName: CBA-ORM-PORT
    - key: CBA-ORM-USERNAME
      objectName: CBA-ORM-USERNAME
    - key: CBA-ORM-PASSWORD
      objectName: CBA-ORM-PASSWORD
    - key: CBA-ORM-SERVICE-NAME
      objectName: CBA-ORM-SERVICE-NAME
    - key: CBA-AZURE-BLOB-STORAGE-WSDL-CONNECTION-STRING
      objectName: CBA-AZURE-BLOB-STORAGE-WSDL-CONNECTION-STRING
    - key: CBA-X-CENTRASITE-APIKEY
      objectName: CBA-X-CENTRASITE-APIKEY 
    - key: CBA-X-FORWARDED-FOR
      objectName: CBA-X-FORWARDED-FOR 
    - key: CBA-CPC-AUTHORISATION
      objectName: CBA-CPC-AUTHORISATION 
    - key: CBA-CPC-PTOKENID
      objectName: CBA-CPC-PTOKENID 
    - key: CBA-DMT-WSDLSECURITY-USERNAME
      objectName: CBA-DMT-WSDLSECURITY-USERNAME 
    - key: CBA-DMT-WSDLSECURITY-PASSWORD 
      objectName: CBA-DMT-WSDLSECURITY-PASSWORD 
    - key: CBA-SZHP-USERNAME 
      objectName: CBA-SZHP-USERNAME 
    - key: CBA-SZHP-PASSWORD 
      objectName: CBA-SZHP-PASSWORD  
    - key: CBA-SZHP-IPHONEAPPKEY 
      objectName: CBA-SZHP-IPHONEAPPKEY 
    - key: CBA-ICP-USERNAME 
      objectName: CBA-ICP-USERNAME 
    - key: CBA-ICP-PASSWORD  
      objectName: CBA-ICP-PASSWORD 
    - key: CBA-HASH-ENCRYPTION-SECRET-KEY  
      objectName: CBA-HASH-ENCRYPTION-SECRET-KEY   
    - key: CBA-X-GATEWAY-APIKEY 
      objectName: CBA-X-GATEWAY-APIKEY                 
    - key: CBA-MOF-USERNAME
      objectName: CBA-MOF-USERNAME                 
    - key: CBA-MOF-PASSWORD
      objectName: CBA-MOF-PASSWORD  
    - key: CBA-APPLICATION-INTEGRATION-CLIENT-ID
      objectName: CBA-APPLICATION-INTEGRATION-CLIENT-ID
    - key: CBA-APPLICATION-INTEGRATION-CLIENT-SECRET
      objectName: CBA-APPLICATION-INTEGRATION-CLIENT-SECRET 
    - key: CBA-CPC-USERNAME
      objectName: CBA-CPC-USERNAME
    - key: CBA-CPC-PASSWORD
      objectName: CBA-CPC-PASSWORD
    - key: CBA-EMIRATE-ID-KEY
      objectName: CBA-EMIRATE-ID-KEY                                                                     
    secretName: {{ .Values.global.secretName }}                      # name of the Kubernetes secret object
    type: Opaque
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: {{ .Values.keyVaultName }}       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: AZURE-APP-INSIGHTS-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-AZURE-BLOB-STORAGE-CONFIG-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-ORM-HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-ORM-PORT
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-ORM-USERNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-ORM-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-ORM-SERVICE-NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-AZURE-BLOB-STORAGE-WSDL-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-RABBITMQ-URI
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-X-CENTRASITE-APIKEY
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-X-FORWARDED-FOR
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-CPC-AUTHORISATION
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-CPC-PTOKENID
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-DMT-WSDLSECURITY-USERNAME
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-DMT-WSDLSECURITY-PASSWORD 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-SZHP-USERNAME 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-SZHP-PASSWORD 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-SZHP-IPHONEAPPKEY 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-ICP-USERNAME 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-ICP-PASSWORD 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-HASH-ENCRYPTION-SECRET-KEY 
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-X-GATEWAY-APIKEY 
          objectType: secret
          objectVersion: ""                                                                                                                                                          
        - |
          objectName: CBA-MOF-USERNAME 
          objectType: secret
          objectVersion: ""                                                                                                                                                          
        - |
          objectName: CBA-MOF-PASSWORD
          objectType: secret
          objectVersion: "" 
        - |
          objectName: CBA-APPLICATION-INTEGRATION-CLIENT-ID
          objectType: secret
          objectVersion: ""  
        - |
          objectName: CBA-APPLICATION-INTEGRATION-CLIENT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-CPC-USERNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-CPC-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: CBA-EMIRATE-ID-KEY
          objectType: secret
          objectVersion: ""                                                                                                                                                              
    tenantId: {{ .Values.keyVaultTenantId }}                # The tenant ID of the key vault
